[package]
name = "patch"
version = "0.4.1"
authors = ["phil <uniphil@gmail.com>"]
description = "Parse patches in the unified diff format"
repository = "https://github.com/uniphil/patch-rs"
readme = "readme.md"
keywords = ["patch", "diff", "parse", "nom"]
license = "MIT"

[dependencies]
nom = "^2.0"
chrono = "^0.2.25"
